package ru.sr2020.database.model.iface;

import ru.sr2020.database.model.pojo.BodyMods;

import java.util.Set;


/**
 * Object interface mapping for hibernate-handled table: bodymodtype.
 *
 * @author autogenerated
 */

public interface IBodymodtype {


    /**
     * Adds a bi-directional link of type BodyMods to the bodyModss set.
     *
     * @param bodyMods item to add
     */
    void addBodyMods(BodyMods bodyMods);

    /**
     * Return the value associated with the column: additionType.
     *
     * @return A String object (this.additionType)
     */
    String getAdditionType();

    /**
     * Set the value related to the column: additionType.
     *
     * @param additionType the additionType value you wish to set
     */
    void setAdditionType(final String additionType);

    /**
     * Return the value associated with the column: additionVal.
     *
     * @return A Integer object (this.additionVal)
     */
    Integer getAdditionVal();

    /**
     * Set the value related to the column: additionVal.
     *
     * @param additionVal the additionVal value you wish to set
     */
    void setAdditionVal(final Integer additionVal);

    /**
     * Return the value associated with the column: bodyMods.
     *
     * @return A Set&lt;BodyMods&gt; object (this.bodyMods)
     */
    Set<BodyMods> getBodyModss();

    /**
     * Set the value related to the column: bodyMods.
     *
     * @param bodyMods the bodyMods value you wish to set
     */
    void setBodyModss(final Set<BodyMods> bodyMods);

    /**
     * Return the value associated with the column: id.
     *
     * @return A Integer object (this.id)
     */
    Integer getId();


    /**
     * Set the value related to the column: id.
     *
     * @param id the id value you wish to set
     */
    void setId(final Integer id);

    /**
     * Return the value associated with the column: name.
     *
     * @return A String object (this.name)
     */
    String getName();


    /**
     * Set the value related to the column: name.
     *
     * @param name the name value you wish to set
     */
    void setName(final String name);

    // end of interface
}
