package ru.sr2020.database.model.iface;

import ru.sr2020.database.model.pojo.Body;
import ru.sr2020.database.model.pojo.Bodymodtype;


/**
 * Object interface mapping for hibernate-handled table: body_mods.
 *
 * @author autogenerated
 */

public interface IBodyMods {


    /**
     * Return the value associated with the column: body.
     *
     * @return A Body object (this.body)
     */
    Body getBody();


    /**
     * Set the value related to the column: body.
     *
     * @param body the body value you wish to set
     */
    void setBody(final Body body);

    /**
     * Return the value associated with the column: bodyModType.
     *
     * @return A Bodymodtype object (this.bodyModType)
     */
    Bodymodtype getBodyModType();


    /**
     * Set the value related to the column: bodyModType.
     *
     * @param bodyModType the bodyModType value you wish to set
     */
    void setBodyModType(final Bodymodtype bodyModType);

    /**
     * Return the value associated with the column: id.
     *
     * @return A Integer object (this.id)
     */
    Integer getId();


    /**
     * Set the value related to the column: id.
     *
     * @param id the id value you wish to set
     */
    void setId(final Integer id);

    // end of interface
}
