package ru.sr2020.database.model.iface;

import ru.sr2020.database.model.pojo.Body;
import ru.sr2020.database.model.pojo.Player;
import ru.sr2020.database.model.pojo.Sin;

import java.util.Set;


/**
 * Object interface mapping for hibernate-handled table: character.
 *
 * @author autogenerated
 */

public interface ICharacter {


    /**
     * Adds a bi-directional link of type Body to the bodies set.
     *
     * @param body item to add
     */
    void addBody(Body body);

    /**
     * Adds a bi-directional link of type Sin to the sins set.
     *
     * @param sin item to add
     */
    void addSin(Sin sin);

    /**
     * Return the value associated with the column: body.
     *
     * @return A Set&lt;Body&gt; object (this.body)
     */
    Set<Body> getBodies();

    /**
     * Set the value related to the column: body.
     *
     * @param body the body value you wish to set
     */
    void setBodies(final Set<Body> body);

    /**
     * Return the value associated with the column: hackerlogin.
     *
     * @return A String object (this.hackerlogin)
     */
    String getHackerlogin();

    /**
     * Set the value related to the column: hackerlogin.
     *
     * @param hackerlogin the hackerlogin value you wish to set
     */
    void setHackerlogin(final String hackerlogin);

    /**
     * Return the value associated with the column: hackerpwd.
     *
     * @return A String object (this.hackerpwd)
     */
    String getHackerpwd();

    /**
     * Set the value related to the column: hackerpwd.
     *
     * @param hackerpwd the hackerpwd value you wish to set
     */
    void setHackerpwd(final String hackerpwd);

    /**
     * Return the value associated with the column: id.
     *
     * @return A Integer object (this.id)
     */
    Integer getId();

    /**
     * Set the value related to the column: id.
     *
     * @param id the id value you wish to set
     */
    void setId(final Integer id);

    /**
     * Return the value associated with the column: player.
     *
     * @return A Player object (this.player)
     */
    Player getPlayer();

    /**
     * Set the value related to the column: player.
     *
     * @param player the player value you wish to set
     */
    void setPlayer(final Player player);

    /**
     * Return the value associated with the column: sin.
     *
     * @return A Set&lt;Sin&gt; object (this.sin)
     */
    Set<Sin> getSins();

    /**
     * Set the value related to the column: sin.
     *
     * @param sin the sin value you wish to set
     */
    void setSins(final Set<Sin> sin);

    /**
     * Return the value associated with the column: status.
     *
     * @return A String object (this.status)
     */
    String getStatus();


    /**
     * Set the value related to the column: status.
     *
     * @param status the status value you wish to set
     */
    void setStatus(final String status);

    /**
     * Return the value associated with the column: truerace.
     *
     * @return A Integer object (this.truerace)
     */
    Integer getTruerace();


    /**
     * Set the value related to the column: truerace.
     *
     * @param truerace the truerace value you wish to set
     */
    void setTruerace(final Integer truerace);

    // end of interface
}
