package ru.sr2020.database.model.iface;

import ru.sr2020.database.model.pojo.Character;


/**
 * Object interface mapping for hibernate-handled table: sin.
 *
 * @author autogenerated
 */

public interface ISin {


    /**
     * Return the value associated with the column: citizenship.
     *
     * @return A Integer object (this.citizenship)
     */
    Integer getCitizenship();


    /**
     * Set the value related to the column: citizenship.
     *
     * @param citizenship the citizenship value you wish to set
     */
    void setCitizenship(final Integer citizenship);

    /**
     * Return the value associated with the column: id.
     *
     * @return A Integer object (this.id)
     */
    Integer getId();


    /**
     * Set the value related to the column: id.
     *
     * @param id the id value you wish to set
     */
    void setId(final Integer id);

    /**
     * Return the value associated with the column: personname.
     *
     * @return A String object (this.personname)
     */
    String getPersonname();


    /**
     * Set the value related to the column: personname.
     *
     * @param personname the personname value you wish to set
     */
    void setPersonname(final String personname);

    /**
     * Return the value associated with the column: race.
     *
     * @return A Integer object (this.race)
     */
    Integer getRace();


    /**
     * Set the value related to the column: race.
     *
     * @param race the race value you wish to set
     */
    void setRace(final Integer race);

    /**
     * Return the value associated with the column: role.
     *
     * @return A Character object (this.role)
     */
    Character getRole();


    /**
     * Set the value related to the column: role.
     *
     * @param role the role value you wish to set
     */
    void setRole(final Character role);

    /**
     * Return the value associated with the column: sintext.
     *
     * @return A String object (this.sintext)
     */
    String getSintext();


    /**
     * Set the value related to the column: sintext.
     *
     * @param sintext the sintext value you wish to set
     */
    void setSintext(final String sintext);

    // end of interface
}
