package ru.sr2020.database.model.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import ru.sr2020.database.model.pojo.Bodymodtype;

/**
 * Spring Data Repository for table: bodymodtype.
 *
 * @author autogenerated/custom
 */
public interface BodymodtypeRepository extends JpaRepository<Bodymodtype, Integer>, QuerydslPredicateExecutor<Bodymodtype> {

    // Add any extra methods here. This file will not get overwritten unlike any other generated file
}
