package ru.sr2020.database.model.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import ru.sr2020.database.model.pojo.Body;

/**
 * Spring Data Repository for table: body.
 *
 * @author autogenerated/custom
 */
public interface BodyRepository extends JpaRepository<Body, Long>, QuerydslPredicateExecutor<Body> {

    // Add any extra methods here. This file will not get overwritten unlike any other generated file
}
