package ru.sr2020.database.model.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import ru.sr2020.database.model.pojo.Character;

/**
 * Spring Data Repository for table: character.
 *
 * @author autogenerated/custom
 */
public interface CharacterRepository extends JpaRepository<Character, Integer>, QuerydslPredicateExecutor<Character> {

    // Add any extra methods here. This file will not get overwritten unlike any other generated file
}
