package ru.sr2020.database.model.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import ru.sr2020.database.model.pojo.Player;

/**
 * Spring Data Repository for table: player.
 *
 * @author autogenerated/custom
 */
public interface PlayerRepository extends JpaRepository<Player, Integer>, QuerydslPredicateExecutor<Player> {

    // Add any extra methods here. This file will not get overwritten unlike any other generated file
}
