package ru.sr2020.database.model.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import ru.sr2020.database.model.pojo.Sin;

/**
 * Spring Data Repository for table: sin.
 *
 * @author autogenerated/custom
 */
public interface SinRepository extends JpaRepository<Sin, Integer>, QuerydslPredicateExecutor<Sin> {

    // Add any extra methods here. This file will not get overwritten unlike any other generated file
}
